const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbmV3cmVzaS5sb2NhbDo3ODg4L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNTQwNzgyOTU4LCJuYmYiOjE1NDA3ODI5NTgsImp0aSI6ImlmT2loWjY1QVptems3dFkiLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.O6O2xse4JOReyQutaAyxjmOGXAxEd3eDDIX1DWT96cI';
const resiUrl = 'https://resi.id/';

module.exports = {
  token,
  resiUrl
};
